### ISSUE TITLE
this repo version is v0.5, not the newest 0.6, can you update this repo? thanks!

### ISSUE THREAD

**Issue by mrhaoll** [hyphop/khadas-openwrt#3]
this repo version is v0.5, not the newest 0.6, can you update this repo? thanks!

#
# OPENWRT build config
#

#REL=19.07.0-rc1
#REL=19.07.0-rc2
REL=19.07.0
REL=18.06.4
VER=v0.5
KERNEL_REL=openwrt.test
KERNEL_REL=openwrt
KERNEL_REL=openwrt.new
LABEL=OPENWRT
BOARD=VIM1
BOARDS="VIM1 VIM2 VIM3 VIM3L"
BITS=64
PART1_LABEL=OW_BOOT
PART2_LABEL=
PART2_1_LABEL=rootfs_data
TARGET=armvirt
OWARCH=aarch64_generic
TARGET_KERNEL_ARCH=arm64
P1OFFSET=4096

**Comment by hyphop** [comment]
update to VER=v0.61
